# Generated by Django 5.2.5 on 2026-04-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(db_column='description', verbose_name='Description')),
                ('completed', models.BooleanField(db_column='completed', default=False, verbose_name='Completed')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'Task',
            },
        ),
    ]
